//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internationalApostille.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string Email { get; set; }
        public Nullable<int> blogPostId { get; set; }
        public string CommentText { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual PagesPost PagesPost { get; set; }
        public virtual BlogPost BlogPost { get; set; }
    }
}
