//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internationalApostille.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int ReportTypeID { get; set; }
        public string ReportMessage { get; set; }
        public System.DateTime ReportDate { get; set; }
    
        public virtual ReportType ReportType { get; set; }
    }
}
