//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internationalApostille.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public State()
        {
            this.Counties = new HashSet<County>();
            this.StateExpeditedFees = new HashSet<StateExpeditedFee>();
            this.StateCountryJurisdictions = new HashSet<StateCountryJurisdiction>();
            this.StateImportantLinks = new HashSet<StateImportantLink>();
            this.StateOffices = new HashSet<StateOffice>();
            this.StatePaymentMethods = new HashSet<StatePaymentMethod>();
            this.ZipCodes = new HashSet<ZipCode>();
        }
    
        public int StateID { get; set; }
        public string StateName { get; set; }
        public string StateAbb { get; set; }
        public bool IsState { get; set; }
        public bool IsRequiredCountyForApostille { get; set; }
        public bool IsRequiredCountyForLegalization { get; set; }
        public decimal FeeApostille { get; set; }
        public decimal FeeLegalization { get; set; }
        public int AroundTime { get; set; }
        public string AroundTimeText { get; set; }
        public string Website { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public bool IsTerritory { get; set; }
        public int WalkinAroundTime { get; set; }
        public string WalkinAroundTimeText { get; set; }
        public Nullable<decimal> WalkinFeeApostille { get; set; }
        public Nullable<decimal> WalkinFeeLegalization { get; set; }
        public string Message { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<County> Counties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateExpeditedFee> StateExpeditedFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateCountryJurisdiction> StateCountryJurisdictions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateImportantLink> StateImportantLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateOffice> StateOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatePaymentMethod> StatePaymentMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZipCode> ZipCodes { get; set; }
    }
}
