//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internationalApostille.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwentyExtraFedexTicket
    {
        public int Id { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<bool> IsExpedited { get; set; }
        public string TrackingToUSDepartment { get; set; }
        public byte[] TrackingToUSDepartmentImage { get; set; }
        public Nullable<int> TrackingToUSDepartmentStatusId { get; set; }
        public string TrackingToEmbassy { get; set; }
        public byte[] TrackingToEmbassyImage { get; set; }
        public Nullable<int> TrackingToEmbassyStatusId { get; set; }
        public string TrackingToCompany { get; set; }
        public byte[] TrackingToCompanyImage { get; set; }
        public Nullable<int> TrackingToCompanyStatusId { get; set; }
    
        public virtual TwentyFedexStatu TwentyFedexStatu { get; set; }
        public virtual TwentyFedexStatu TwentyFedexStatu1 { get; set; }
        public virtual TwentyRequest TwentyRequest { get; set; }
    }
}
