//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internationalApostille.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class USDBEntities : DbContext
    {
        public USDBEntities()
            : base("name=USDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carrier> Carriers { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CountryImportantLink> CountryImportantLinks { get; set; }
        public virtual DbSet<CountryPaymentMethod> CountryPaymentMethods { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<CountyPaymentMethod> CountyPaymentMethods { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<Embassy> Embassies { get; set; }
        public virtual DbSet<EmbassyCarrier> EmbassyCarriers { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportType> ReportTypes { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<RequestCountry> RequestCountries { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<StateCountryJurisdiction> StateCountryJurisdictions { get; set; }
        public virtual DbSet<StateExpeditedFee> StateExpeditedFees { get; set; }
        public virtual DbSet<StateImportantLink> StateImportantLinks { get; set; }
        public virtual DbSet<StateOffice> StateOffices { get; set; }
        public virtual DbSet<StateOfficeCarrier> StateOfficeCarriers { get; set; }
        public virtual DbSet<StatePaymentMethod> StatePaymentMethods { get; set; }
        public virtual DbSet<TwentyContactInfoData> TwentyContactInfoDatas { get; set; }
        public virtual DbSet<TwentyExtraFedexTicket> TwentyExtraFedexTickets { get; set; }
        public virtual DbSet<TwentyFedexStatu> TwentyFedexStatus { get; set; }
        public virtual DbSet<TwentyRequest> TwentyRequests { get; set; }
        public virtual DbSet<USDepartment> USDepartments { get; set; }
        public virtual DbSet<USDepartmentImportantLink> USDepartmentImportantLinks { get; set; }
        public virtual DbSet<USDepartmentPaymentMethod> USDepartmentPaymentMethods { get; set; }
        public virtual DbSet<ZipCode> ZipCodes { get; set; }

        public System.Data.Entity.DbSet<internationalApostille.Models.BlogPost> BlogPosts { get; set; }

        public System.Data.Entity.DbSet<internationalApostille.Models.Category> Categories { get; set; }

        public System.Data.Entity.DbSet<internationalApostille.Models.User> Users { get; set; }
    }
}
