//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internationalApostille.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USDepartmentPaymentMethod
    {
        public int USDepartmentPaymentMethodID { get; set; }
        public int USDepartmentID { get; set; }
        public int PaymentMethodID { get; set; }
        public string PayableTo { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual USDepartment USDepartment { get; set; }
    }
}
