//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internationalApostille.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USDepartment()
        {
            this.USDepartmentImportantLinks = new HashSet<USDepartmentImportantLink>();
            this.USDepartmentPaymentMethods = new HashSet<USDepartmentPaymentMethod>();
        }
    
        public int USDepartmentID { get; set; }
        public string USDepartmentName { get; set; }
        public decimal Fee { get; set; }
        public int MailAroundTime { get; set; }
        public string WalkAroundTimeText { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string MailAddress { get; set; }
        public string ZipCode { get; set; }
        public string WalkAddress { get; set; }
        public string POAddress { get; set; }
        public string PODepartmentName { get; set; }
        public string POZipCodeExtention { get; set; }
    
        public virtual ZipCode ZipCode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USDepartmentImportantLink> USDepartmentImportantLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USDepartmentPaymentMethod> USDepartmentPaymentMethods { get; set; }
    }
}
